//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesGS
    {
        public int ID_Cliente { get; set; }
        public string Nom_Cliente { get; set; }
        public Nullable<int> Identificacion_CGS { get; set; }
        public Nullable<int> Tel_Cliente { get; set; }
        public string Email_Cliente { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
    
        public virtual MetodoPagoGS MetodoPagoGS { get; set; }
    }
}
