//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosGS
    {
        public int ID_Empleado { get; set; }
        public string Nom_Empleado { get; set; }
        public string Cedula_Empleado { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Telefono { get; set; }
        public string Ocupacion_Empleado { get; set; }
        public Nullable<double> Salario_Empleado { get; set; }
        public Nullable<int> IdCargoEmp { get; set; }
        public Nullable<int> IdDepEmp { get; set; }
    
        public virtual DepartamentoGS DepartamentoGS { get; set; }
        public virtual EmpleadoCargoGS EmpleadoCargoGS { get; set; }
    }
}
