//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPagoGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetodoPagoGS()
        {
            this.ClientesGS = new HashSet<ClientesGS>();
        }
    
        public int IdMetodoPago { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdProveedorPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesGS> ClientesGS { get; set; }
        public virtual ProveedorPagoGS ProveedorPagoGS { get; set; }
    }
}
