//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeltlemenStoreEntities : DbContext
    {
        public GeltlemenStoreEntities()
            : base("name=GeltlemenStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaGS> CategoriaGS { get; set; }
        public virtual DbSet<ClientesGS> ClientesGS { get; set; }
        public virtual DbSet<DepartamentoGS> DepartamentoGS { get; set; }
        public virtual DbSet<EmpleadoCargoGS> EmpleadoCargoGS { get; set; }
        public virtual DbSet<EmpleadosGS> EmpleadosGS { get; set; }
        public virtual DbSet<MetodoPagoGS> MetodoPagoGS { get; set; }
        public virtual DbSet<ProductosGS> ProductosGS { get; set; }
        public virtual DbSet<ProveedorPagoGS> ProveedorPagoGS { get; set; }
        public virtual DbSet<SubCategoriaGS> SubCategoriaGS { get; set; }
        public virtual DbSet<SuplidoresGS> SuplidoresGS { get; set; }
    }
}
