//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosGS
    {
        public int ID_Productos { get; set; }
        public string Nom_Producto { get; set; }
        public string Tipo_Producto { get; set; }
        public Nullable<int> Cantidad_Producto { get; set; }
        public Nullable<int> CostoU_Producto { get; set; }
        public Nullable<int> Suplidor_P { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdSubCategoria { get; set; }
    
        public virtual CategoriaGS CategoriaGS { get; set; }
        public virtual SubCategoriaGS SubCategoriaGS { get; set; }
        public virtual SuplidoresGS SuplidoresGS { get; set; }
    }
}
