//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoriaGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategoriaGS()
        {
            this.ProductosGS = new HashSet<ProductosGS>();
        }
    
        public int Id_SubCategoria { get; set; }
        public string NombreSubcategoria { get; set; }
        public Nullable<int> IdCategoria { get; set; }
    
        public virtual CategoriaGS CategoriaGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosGS> ProductosGS { get; set; }
    }
}
