//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentlemanStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuplidoresGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuplidoresGS()
        {
            this.ProductosGS = new HashSet<ProductosGS>();
        }
    
        public int ID_Suplidor { get; set; }
        public string Nom_Suplidor { get; set; }
        public Nullable<int> RNC_Suplidor { get; set; }
        public string Dirrec_Suplidor { get; set; }
        public Nullable<int> Tel_Suplidor { get; set; }
        public string Email_Suplidor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosGS> ProductosGS { get; set; }
    }
}
